defmodule FariaLimaOasis.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vaga_areas, primary_key: false) do
      add :vaga_id,
          references(:vagas,
            column: :id,
            name: "vaga_areas_vaga_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :area_id,
          references(:areas,
            column: :id,
            name: "vaga_areas_area_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:vaga_areas, "vaga_areas_vaga_id_fkey")

    drop constraint(:vaga_areas, "vaga_areas_area_id_fkey")

    drop table(:vaga_areas)
  end
end
