defmodule FariaLimaOasis.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:empresas) do
      add :logo_url, :text
    end
  end

  def down do
    alter table(:empresas) do
      remove :logo_url
    end
  end
end
