defmodule FariaLimaOasis.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vagas) do
      modify :pdf_url, :text, null: false
      modify :text_content, :text, null: false
      modify :title, :text, null: false
    end

    alter table(:areas) do
      modify :acronym, :text, null: false
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:areas) do
      modify :name, :text, null: true
      modify :acronym, :text, null: true
    end

    alter table(:vagas) do
      modify :title, :text, null: true
      modify :text_content, :text, null: true
      modify :pdf_url, :text, null: true
    end
  end
end
