defmodule FariaLimaOasis.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :avatar_url, :text, default: "/images/default_profile_pic.jpg"
    end
  end

  def down do
    alter table(:users) do
      remove :avatar_url
    end
  end
end
