defmodule FariaLimaOasis.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :text_content, :text, null: false
      add :pdf_url, :text, null: false
      add :type, :text, null: false

      add :empresa_id,
          references(:empresas,
            column: :id,
            name: "results_empresa_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:result_areas, primary_key: false) do
      add :result_id,
          references(:results,
            column: :id,
            name: "result_areas_result_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :area_id,
          references(:areas,
            column: :id,
            name: "result_areas_area_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:result_areas, "result_areas_result_id_fkey")

    drop constraint(:result_areas, "result_areas_area_id_fkey")

    drop table(:result_areas)

    drop constraint(:results, "results_empresa_id_fkey")

    drop table(:results)
  end
end
